### ISSUE TITLE
PDF/A-3u with embedfile missing /AF entry and /AFRelationship entry

### ISSUE THREAD

**Issue by wollmich** [ho-tex/embedfile#1]
I'm having the following data file called `data.txt`:

    Testdata

and the following LaTeX code called `test2.tex`:

    \documentclass{article}
    
    \usepackage[a-3u]{pdfx}
    \usepackage{embedfile}
    \newcommand{\datafile}[2]{\embedfile[filespec={#2},ucfilespec={#2},filesystem=URL,mimetype=application/octet-stream,desc={#2},stringmethod=escape]{#1#2}}
    
    \datafile{}{data.txt}
    
    \begin{document}
    Bla bla ...
    \end{document}
    
Using `pdfLaTeX` I can generate a PDF which claims that it is PDF/A-3u.

If I verify this PDF with Adobe Preflight I get the following errors:

- Embedded file does not have /AF entry
- Embedded file has no /AFRelationship entry

[![enter image description here][1]][1]

I found the following source describing the /AF entry and the /AFRelationship entry, see https://arxiv.org/pdf/1406.6126.pdf. I do not fully understand it.

If I take a look at the uncompressed pdf file, where the embed file is described, it looks like that:

    5 0 obj
    <</Type/Filespec/FS/URL/F(data.txt)/UF(data.txt)/Desc(data.txt)/EF<</F 4 0 R>>>>
    endobj

If this would be changed to

    5 0 obj
    <</Type/Filespec/FS/URL/F(data.txt)/UF(data.txt)/Desc(data.txt)/AFRelationship/Unspecified/EF<</F 4 0 R>>>>
    endobj

then there should be no missing /AFRelationship entry anymore.

And somewhere there should be `/AF[5 0 R 5 0 R]` to solve the missing /AF entry.

Can the `embedfile` package be improved so that it adds as well the /AF entry and the /AFRelationship entry?

See as well https://tex.stackexchange.com/questions/426385/pdf-a-3u-with-embedfile-missing-af-entry-and-afrelationship-entry.

[1]: https://i.stack.imgur.com/cKbZt.png

**Comment by viktoriasee** [comment]
The new version is doing a great job except for the combination of [LuaTeX and hyperref](https://tex.stackexchange.com/questions/536350/embed-a-file-with-luatex-and-hyperref-and-setting-afrelationship/536363).

I also recommend mentioning the new key in the documentation, section `User interface`.
