### ISSUE TITLE
\embedfilesetup gives "\KVS@@Process has an extra }" error

### ISSUE THREAD

**Issue by dbitouze** [ho-tex/embedfile#2]
After recent TeX Live update (if I'm right, in particular of packages `kvdefinekeys` (53167), `kvsetkeys` (53166) and `ltxcmds` (53165)), the following MCE:

```latex
\documentclass{article}
\usepackage{embedfile}
\embedfilesetup{view=details}
\begin{document}
Test.
\end{document}
```

fails to compile with the following error:

```
! Argument of \KVS@@Process has an extra }.
<inserted text> 
                \par 
l.23 \kv@define@key{EmFi}{view}[]
                                 {}
```

and this, only if the `\embedfilesetup{view=...}` is used.

Here is the file list:

```
 *File List*
 article.cls    2019/10/25 v1.4k Standard LaTeX document class
  size10.clo    2019/10/25 v1.4k Standard LaTeX file (size option)
embedfile.sty    2019/12/03 v2.9 Embed files into PDF (HO)
infwarerr.sty    2019/12/03 v1.5 Providing info/warning/error messages (HO)
   iftex.sty    2019/11/07 v1.0c TeX engine tests
pdftexcmds.sty    2019/11/24 v0.31 Utility functions of pdfTeX for LuaTeX (HO)
 ltxcmds.sty    2019/12/15 v1.24 LaTeX kernel commands for general use (HO)
kvsetkeys.sty    2019/12/15 v1.18 Key value parser (HO)
kvdefinekeys.sty    2019/12/15 v1.5 Define keys (HO)
pdfescape.sty    2019/12/09 v1.15 Implements pdfTeX's escape features (HO)
 ***********
```

**Comment by davidcarlisle** [comment]
Thanks I can confirm the error, I'll trace in a bit, there are very few code changes here so should be easy to track down, sorry for the inconvenience.  The issue appears to be in kvdefinekeys.sty (the example works if I copy in the old version of that)  I'll trace later and should update today, thanks for the report

**Comment by u-fischer** [comment]
The key has an optional argument in the definition and there the processing is wrong

`\kv@define@key{EmFi}{view}[]{%`

**Comment by davidcarlisle** [comment]
@dbitouze  This works I believe

```
 \documentclass{article}
 
 \usepackage{kvdefinekeys}
 \makeatletter
 \def\KVD@DefineKey#1#2{%
   \begingroup
    \toks\z@{\endgroup\KVD@DefineKeyWithDefault{#1}{#2}}%
    \toks\tw@{\endgroup\long\expandafter\def\csname KV@#1@#2\endcsname##1}%
   \@ifnextchar[{\the\toks\z@}{\the\toks\tw@}%
 }
 \makeatother
 
 \usepackage{embedfile}
 
 
 
 \embedfilesetup{view=details}
 \begin{document}
 Test.
 \end{document}
```

**Comment by dbitouze** [comment]
@davidcarlisle 

>This works I believe

Well, not for me. This file fails to compile with the following error:

```
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.244 \EmFi@DefineKey{mimetype}{}
```

**Comment by davidcarlisle** [comment]
@davidcarlisle  sorry cut and paste error into github the checked in file is OK but the comment above has `@ifnextchar` with no backslash should be `\@ifnextchar` (I'll edit the comment for future readers)

**Comment by davidcarlisle** [comment]
@dbitouze  sorry that was a markdown error, I marked the region with `>` instead of backticks and so `\@` appeared as `@` and scrambled the display, please see the updated comment above or the version checked in to the kvdefinekeys repository

**Comment by dbitouze** [comment]
@davidcarlisle Sorry to not having detected this typo. Works  like a charm now, with the MCE above and with real documents as well: thanks!

**Comment by davidcarlisle** [comment]
kvdefinekeys has been submitted to ctan
