### ISSUE TITLE
feature: package option Source

### ISSUE THREAD

**Issue by viktoriasee** [ho-tex/embedfile#3]
I absolutely love this package. I would like to include the source of my documents by default. Right now this is possible but it takes a while to find the correct command.

### Minimal Example
```latex
\documentclass{article} 
\usepackage{embedfile}
\embedfile[mimetype={application/x-tex},afrelationship={/Source},ucfilespec={\jobname.tex}]{\jobname.tex}
\begin{document} 
Hello, world! 
\end{document}
```

### desired behaviour
Change the package so the code below produces the same output as the minimal example above.
```latex
\documentclass{article} 
\usepackage[Source]{embedfile}
\begin{document} 
Hello, world! 
\end{document}
```

**Comment by u-fischer** [comment]
Imho you are asking for an option for a rather special and restricted use case. 

Why should this option (and embedfile has currently no option, so it would be a rather prominent one) embed only `\jobname.tex`? Why not also files that are `\input` or `\include`? Or listings? All this files are "source files" too.

No, I don't think that makes sense. If you found it difficult to setup the options: Sent a list of useful examples and I will add them to the documentation.

**Comment by viktoriasee** [comment]
> Why not also files that are \input or \include?

Good question. I usually have one file. But for those who use additional files it makes sense to include all of them. Why would that not make sense? Imo most users of `embedfile` will at least embed the source, won't they? Next candidates are raw data from the appendix etc. It's a good default to include the source in case a document needs to be modified later.

Since it is maybe not trivial to catch all include files you get a solution that covers 80% just by implementing the simple solution I proposed. One can still extend the solution later.

**Comment by u-fischer** [comment]
> Why would that not make sense?

Because embedfile is about the technical aspects how to embed files, not about "which sets in which order could user perhaps want to embed".  When you start this you soon have to consider, what to do with images, data-files, bib-files, glossaries, acronyms and end with a complete new package with lots of options. 

So no, if you want to start with this, write your own package.

**Comment by davidcarlisle** [comment]
On Wed, 1 Apr 2020 at 10:57, viktoriasee <notifications@github.com> wrote:

>  Imo most users of embedfile will at least embed the source, won't they?


I would doubt it to be honest. I don't think I've ever seen a pdf document
with sources embedded, so this seems to be a very specialised use case.
Embedding files at all is rather rare (especially as not all PDF readers
make it easy or possible to extract the files) but as Ulrike said it's not
possible to second guess which files the author wants to embed and an
option which just embeds the top level source file without embedding input
documents and images would do more harm than good.

**Comment by davidcarlisle** [comment]
Closing as this is beyond the scope of this package.

**Comment by viktoriasee** [comment]
> So no, if you want to start with this, write your own package.

Not neccessary, the package already exists. It's called [`embedall`](https://ctan.org/pkg/embedall).

> I would doubt it to be honest. I don't think I've ever seen a pdf document
with sources embedded, so this seems to be a very specialised use case.

Have you seen how many upvotes the [question](https://tex.stackexchange.com/a/418609/50129) got on stackexchange? This is a popular (indirect) usage of `embedfile`! Maybe it's worth mentioning embedall in the embedfile doc?
